version: "3"
services:
  app:
    image: dmitriyshub/tmdb-api:latest
    #build: .
    volumes:
      - ./secret:/app/secret
    depends_on:
      - db_host
    ports:
        - "8080:8080"
    restart: always
  db_host:
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always